name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install --upgrade pip wheel
      - run: pip install bandit black codespell flake8 flake8-bugbear flake8-comprehensions
                         flake8-return isort mypy pep8-naming pytest pyupgrade safety
      - run: bandit --recursive --skip B311,B605 .
      - run: black --check . || true
      - run: codespell --ignore-words-list=ans
      - run: flake8 . --count --max-complexity=19 --max-line-length=88 --show-source --statistics
      - run: isort --check-only --profile black .
      - run: sudo apt-get install libespeak-dev portaudio19-dev
      - run: pip install -r requirements.txt
      - run: mkdir --parents --verbose .mypy_cache
      - run: mypy --ignore-missing-imports --install-types --non-interactive .
      - run: pytest . || true
      - run: pytest --doctest-modules . || true
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py
      - run: safety check
